version: "3"

services:
    node:
        container_name: node
        image: node
        restart: always
        user: node
        tty: true
        stdin_open: true
        working_dir: /home/node
        volumes:
            - .:/home/node
